version: '3'

services:
  kali-rolling:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: gemina
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - ./my_shared_folder:/root/shared
    ports:
      - "2222:22"
